name: Check Run workflow

on:
  pull_request:
    types: [labeled]

env:
  BUILD_URL: '${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}'
  PR_NUMBER: ${{ github.event.pull_request.number }}

jobs:
  adding-check-run:
    if: github.event.label.name == 'test'
    timeout-minutes: 5
    runs-on: ubuntu-latest


    steps:
      - name: 'Checkout code'
        uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install yarn
        id: install-yarn
        run: npm install -g yarn
